#!/bin/sh

set -e

echo "Building Jekyll site"

bundle exec jekyll build

if test -e "./_site/resume.html";then
  echo "It smokes!"
  cp -rfv ./_site/resume.html ../index.html && cp -rfv ./_site/css/ ../
else
  echo "Build Spanish version failed"
  exit 1
fi
